# TODO: Consider enabling PR comments, etc, after finding coverage bar.
# For now, just make it easy to view it by uploading without reporting.

comment: false
coverage:
  status:
    project: off
    patch: off

ignore:
  # TODO: Run tests after next Envoy release.
  - "src/asgi/websocket/**"
