name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.lock"
      - "bench/**"
      - ".github/workflows/bench.yaml"
  # Just verify the harness on PRs, no need for actual numbers
  pull_request:
    paths:
      - "bench/**"
      - ".github/workflows/bench.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # Overkill to benchmark with every Python version, we just use the latest.
        python:
          - "3.14"
          - "3.14t"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - run: rustup update

      - run: cargo install --features http3 oha

      - run: uv sync --python ${{ matrix.python }} --managed-python

      - run: uv run poe bench ${{ github.event_name == 'pull_request' && '--short' || '' }}
