name: Benchmark
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.lock"
      - "bench/**"
      - ".github/workflows/bench.yaml"
  # Just verify the harness on PRs, no need for actual numbers
  pull_request:
    paths:
      - "bench/**"
      - ".github/workflows/bench.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # Overkill to benchmark with every Python version, we just use the latest.
        python:
          - "3.14"
          - "3.14t"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0

      - run: rustup update

      - run: cargo install --features http3 oha

      - run: uv sync --python ${{ matrix.python }} --managed-python

      - run: uv run poe bench ${{ github.event_name == 'pull_request' && '--short' || '' }}
