name: Renovate Dependencies

on:
  schedule:
    # https://crontab.guru/#5_12_*_*_1
    - cron: "5 12 * * 1"
  workflow_dispatch:

# Uses app token so default token needs no permissions
permissions: {}

jobs:
  renovate:
    uses: curioswitch/go-build/.github/workflows/export-renovate.yaml@8cee71a440fb70ec08525081efdf8088d2b3618e # v0.8.3
    with:
      github_app_id: "1047503"
    secrets:
      github_app_key: ${{ secrets.CURIOSWITCH_APP_KEY }}
